title: Jinsung Ha
url: "https://jha929.github.io/"
baseurl: ""

markdown: kramdown

footer: yes
footer_url: "https://github.com/jha929"
footer_text: "references available upon request"

sass:
  style: compressed
  sass_dir: _sass

