title: Jinsung Ha (하진성)
url: "https://resume.jinsungha.com"
baseurl: "/"

markdown: kramdown

tracking_id: G-J54180QFZD

footer: yes
footer_url: "mailto:jsung5381@naver.com"
footer_text: "references available upon request"

sass:
  style: compressed
  sass_dir: _sass
