title: Jinsung Ha (하진성)
url: "https://www.jinsungha.com"
baseurl: ""

markdown: kramdown

tracking_id: G-J54180QFZD

footer: yes
footer_url: "mailto:jsung5381@naver.com"
footer_text: "references available upon request"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "Github"
    link: "https://github.com/94929"
  - name: "Portfolio"
    link: "https://jinsungha.notion.site/jinsungha/12716fbd7f154ac4a776ba206b950061"
