title: Researcher
url: "https://jha929.github.io/"
#baseurl: "/researcher"
baseurl: ""

markdown: kramdown

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
  style: compressed
  sass_dir: _sass

