title: Jinsung Ha (하진성)
url: "https://www.jinsungha.com"
baseurl: ""

markdown: kramdown

tracking_id: G-J54180QFZD

footer: yes
footer_url: "mailto:jsung5381@naver.com"
footer_text: "references available upon request"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "Home"
    link: "/"
  - name: "Projects"
    link: "https://jinsungha.notion.site/12716fbd7f154ac4a776ba206b950061?pvs=4"
  - name: "Blog"
    link: "https://jinsungha.notion.site/28c93f748745437ebe6b3b6844b25e18?pvs=4"
