title: Jinsung Ha (하진성)
url: "https://jha929.github.io/"
baseurl: ""

markdown: kramdown

footer: yes
footer_url: "mailto:jsung5381@naver.com"
footer_text: "references available upon request"

sass:
  style: compressed
  sass_dir: _sass
